name: Issues Greeting

on:
  issues:
    types: [opened]

jobs:
  issue_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Hey Welcome to portfolioshop🌟. Congratulations on your first issue. We'll figure out something about it soon.\nGentle reminder:\n* Did you go through all of the troubleshooting steps outlined in README.md?"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
